all:
	g++ -static test7-1-1.cpp -o test7-1-1 -L../../lib -lmy_daemon
	g++ -static test7-1-2.cpp -o test7-1-2 -L../../lib -lmy_daemon
	g++ -static test7-2-1.cpp -o test7-2-1 -L../../lib -lmy_daemon
	g++ -static test7-2-2.cpp -o test7-2-2 -L../../lib -lmy_daemon

clean:
	rm test7-1-1 test7-1-2 test7-2-1 test7-2-2

