all:
	g++ -static test2-1.cpp -o test2-1 -L../../lib -lmy_daemon
	g++ -static test2-2.cpp -o test2-2 -L../../lib -lmy_daemon
	g++ -static test2-3.cpp -o test2-3 -L../../lib -lmy_daemon
	g++ -static test2-4-1.cpp -o test2-4-1 -L../../lib -lmy_daemon
	g++ -static test2-4-2.cpp -o test2-4-2 -L../../lib -lmy_daemon
	g++ -static test2-5-1.cpp -o test2-5-1 -L../../lib -lmy_daemon
	g++ -static test2-5-2.cpp -o test2-5-2 -L../../lib -lmy_daemon
clean:
	rm test2-1 test2-2 test2-3 test2-4-1 test2-4-2 test2-5-1 test2-5-2

