all:
	g++ -static test4-1.cpp -o test4-1 -L../../lib -lmy_daemon
	g++ -static test4-2.cpp -o test4-2 -L../../lib -lmy_daemon
	g++ -static test4-3.cpp -o test4-3 -L../../lib -lmy_daemon
	g++ -static test4-4-1.cpp -o test4-4-1 -L../../lib -lmy_daemon
	g++ -static test4-4-2.cpp -o test4-4-2 -L../../lib -lmy_daemon
	g++ -static test4-5-1.cpp -o test4-5-1 -L../../lib -lmy_daemon
	g++ -static test4-5-2.cpp -o test4-5-2 -L../../lib -lmy_daemon
clean:
	rm test4-1 test4-2 test4-3 test4-4-1 test4-4-2 test4-5-1 test4-5-2

