all:
	g++ -static test3-1.cpp -o test3-1 -L../../lib -lmy_daemon
	g++ -static test3-2-1.cpp -o test3-2-1 -L../../lib -lmy_daemon
	g++ -static test3-2-2.cpp -o test3-2-2 -L../../lib -lmy_daemon

clean:
	rm test3-1 test3-2-1 test3-2-2

