all:
	g++ -static test5-1.cpp -o test5-1 -L../../lib -lmy_daemon
	g++ -static test5-2-1.cpp -o test5-2-1 -L../../lib -lmy_daemon
	g++ -static test5-2-2.cpp -o test5-2-2 -L../../lib -lmy_daemon

clean:
	rm test5-1 test5-2-1 test5-2-2

