all:
	g++ -static test6-1-1.cpp -o test6-1-1 -L../../lib -lmy_daemon
	g++ -static test6-1-2.cpp -o test6-1-2 -L../../lib -lmy_daemon
	g++ -static test6-2-1.cpp -o test6-2-1 -L../../lib -lmy_daemon
	g++ -static test6-2-2.cpp -o test6-2-2 -L../../lib -lmy_daemon

clean:
	rm test6-1-1 test6-1-2 test6-2-1 test6-2-2

