all:
	g++ -static test1-1.cpp -o test1-1 -L../../lib -lmy_daemon
	g++ -static test1-2.cpp -o test1-2 -L../../lib -lmy_daemon
	g++ -static test1-3.cpp -o test1-3 -L../../lib -lmy_daemon
clean:
	rm test1-1 test1-2 test1-3

